[app]
  #app名称
  name = "jdcrontab"
  url = "http://localhost"
  port = ":8080"
  debug = false
  appOwner = "fanjinlong"

[database]
  dirver = "mysql"

[mysql]
  dbname = "@tcp(127.0.0.1:3306)/test?charset=utf8"
  username = "root"
  password = "123"

[website]
  static_uri = "/static"
  site_title = "后台管理"
  copy_right = "<small>&copy;2020</small>"

[redis]
  network = "tcp"
  addr = "127.0.0.1:6379"
  password = ""
  database = ""
  maxIdle = 0
  maxActive = 10
  # default 0 is use iris default set
  idleTimeout = 0
  prefix = ""

[session]
  cookie = "sessionscookieid"
  # expires time is set in minute
  expires = 1
  dirver = "native"